export const CATEGORIES = [
    "Sitios naturales",
    "Manifestaciones Culturales",
    "Folclore",
    "Contemporáneas",
    "Acontecimientos Programados",
];

export const DISTRICT_OPTIONS = [
    "Acolla",
    "Apata",
    "Ataura",
    "Canchayllo",
    "Curicaca",
    "El Mantaro",
    "Huamalí",
    "Huaripampa",
    "Huertas",
    "Janjaillo",
    "Jauja",
    "Julcán",
    "Leonor Ordoñez",
    "Llocllapampa",
    "Marco",
    "Masma",
    "Masma Chicche",
    "Molinos",
    "Monobamba",
    "Muqui",
    "Muquiyauyo",
    "Paca",
    "Paccha",
    "Pancán",
    "Parco",
    "Pomacancha",
    "Ricrán",
    "San Lorenzo",
    "San Pedro de Chunán",
    "Sausa",
    "Sincos",
    "Tunan Marca",
    "Yauli",
    "Yauyos"
]