INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('catedral-de-san-antonio-de-huancavelica', 'Catedral de San Antonio de Huancavelica', '', '2. MANIFESTACIONES CULTURALES', 'HUANCAVELICA, HUANCAVELICA, HUANCAVELICA', 'HUANCAVELICA', 'HUANCAVELICA', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('iglesia-de-san-francisco', 'Iglesia de San Francisco', '', '2. MANIFESTACIONES CULTURALES', 'HUANCAVELICA, HUANCAVELICA, HUANCAVELICA', 'HUANCAVELICA', 'HUANCAVELICA', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('iglesia-de-santo-domingo', 'Iglesia de Santo Domingo', '', '2. MANIFESTACIONES CULTURALES', 'HUANCAVELICA, HUANCAVELICA, HUANCAVELICA', 'HUANCAVELICA', 'HUANCAVELICA', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('iglesia-san-juan-de-dios', 'Iglesia San Juan de Dios', '', '2. MANIFESTACIONES CULTURALES', 'HUANCAVELICA, HUANCAVELICA, HUANCAVELICA', 'HUANCAVELICA', 'HUANCAVELICA', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('iglesia-del-barrio-de-santa-ana', 'Iglesia del Barrio de Santa Ana', '', '2. MANIFESTACIONES CULTURALES', 'HUANCAVELICA, HUANCAVELICA, HUANCAVELICA', 'HUANCAVELICA', 'HUANCAVELICA', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('iglesia-de-asuncion', 'Iglesia de Asunción', '', '2. MANIFESTACIONES CULTURALES', 'ASCENSION, HUANCAVELICA, HUANCAVELICA', 'ASCENSION', 'HUANCAVELICA', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('iglesia-de-ascension', 'Iglesia de Ascension', '', '2. MANIFESTACIONES CULTURALES', 'ASCENSION, HUANCAVELICA, HUANCAVELICA', 'ASCENSION', 'HUANCAVELICA', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('iglesia-de-yauli', 'Iglesia de Yauli', '', '2. MANIFESTACIONES CULTURALES', 'YAULI, HUANCAVELICA, HUANCAVELICA', 'YAULI', 'HUANCAVELICA', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('iglesia-de-huando', 'Iglesia de Huando', '', '2. MANIFESTACIONES CULTURALES', 'HUANDO, HUANCAVELICA, HUANCAVELICA', 'HUANDO', 'HUANCAVELICA', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('puente-de-calicanto-de-huaytara', 'Puente de Calicanto de Huaytara', '', '2. MANIFESTACIONES CULTURALES', 'HUAYTARA, HUAYTARA, HUANCAVELICA', 'HUAYTARA', 'HUAYTARA', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('sitio-arqueologico-de-cochapata', 'Sitio Arqueológico de Cochapata', '', '2. MANIFESTACIONES CULTURALES', 'ARMAS, HUAYTARA, HUANCAVELICA', 'ARMAS', 'HUAYTARA', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('sitio-arqueologico-de-tinki-tinki', 'Sitio Arqueológico de Tinki Tinki', '', '2. MANIFESTACIONES CULTURALES', 'SANTOS ORMEO, HUAYTARA, HUANCAVELICA', 'SANTOS ORMEO', 'HUAYTARA', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('sitio-arqueologico-de-inca-machay', 'Sitio Arqueológico de Inca Machay', '', '2. MANIFESTACIONES CULTURALES', 'SANTOS ORMEO, HUAYTARA, HUANCAVELICA', 'SANTOS ORMEO', 'HUAYTARA', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('iglesia-matriz-san-juan-bautista', 'Iglesia Matriz San Juan Bautista', '', '2. MANIFESTACIONES CULTURALES', 'COLCA, HUAYTARA, HUANCAVELICA', 'COLCA', 'HUAYTARA', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('capilla-de-huayucachi', 'Capilla de Huayucachi', '', '2. MANIFESTACIONES CULTURALES', 'SANGAYAICO, HUAYTARA, HUANCAVELICA', 'SANGAYAICO', 'HUAYTARA', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('sitio-arqueologico-de-jarpampac', 'Sitio Arqueológico de Jarpampac', '', '2. MANIFESTACIONES CULTURALES', 'SANGAYAICO, HUAYTARA, HUANCAVELICA', 'SANGAYAICO', 'HUAYTARA', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('sitio-arqueologico-de-huaracco-machay', 'Sitio Arqueológico de Huaracco Machay', '', '2. MANIFESTACIONES CULTURALES', 'QUERCO, HUAYTARA, HUANCAVELICA', 'QUERCO', 'HUAYTARA', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('iglesia-matriz-de-huaytara', 'Iglesia Matriz de Huaytará', '', '2. MANIFESTACIONES CULTURALES', 'HUAYTARA, HUAYTARA, HUANCAVELICA', 'HUAYTARA', 'HUAYTARA', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('templo-inca-de-huaytara', 'Templo Inca de Huaytará', '', '2. MANIFESTACIONES CULTURALES', 'HUAYTARA, HUAYTARA, HUANCAVELICA', 'HUAYTARA', 'HUAYTARA', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('iglesia-de-lircay', 'Iglesia de Lircay', '', '2. MANIFESTACIONES CULTURALES', 'LIRCAY, ANGARAES, HUANCAVELICA', 'LIRCAY', 'ANGARAES', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('sitio-arqueologico-de-willca-chacra', 'Sitio Arqueológico de Willca Chacra', '', '2. MANIFESTACIONES CULTURALES', 'ANCHONGA, ANGARAES, HUANCAVELICA', 'ANCHONGA', 'ANGARAES', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('sitio-arqueologico-de-chonta', 'Sitio Arqueológico de Chonta', '', '2. MANIFESTACIONES CULTURALES', 'LIRCAY, ANGARAES, HUANCAVELICA', 'LIRCAY', 'ANGARAES', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('baños-termales-de-huapa-machay', 'Baños Termales de Huapa Machay', '', '1. SITIOS NATURALES', 'SECLLA, ANGARAES, HUANCAVELICA', 'SECLLA', 'ANGARAES', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('sitio-arqueologico-de-rumichaka', 'Sitio Arqueológico de Rumichaka', '', '2. MANIFESTACIONES CULTURALES', 'LIRCAY, ANGARAES, HUANCAVELICA', 'LIRCAY', 'ANGARAES', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('pueblo-de-anchonga', 'Pueblo de Anchonga', '', '2. MANIFESTACIONES CULTURALES', 'ANCHONGA, ANGARAES, HUANCAVELICA', 'ANCHONGA', 'ANGARAES', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('iglesia-de-lodoy', 'Iglesia de Lodoy', '', '2. MANIFESTACIONES CULTURALES', 'CONGALLA, ANGARAES, HUANCAVELICA', 'CONGALLA', 'ANGARAES', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('iglesia-de-cconccayllu', 'Iglesia de Cconccayllu', '', '2. MANIFESTACIONES CULTURALES', 'LIRCAY, ANGARAES, HUANCAVELICA', 'LIRCAY', 'ANGARAES', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('sitio-arqueologico-de-carhuancho', 'Sitio Arqueológico de Carhuancho', '', '2. MANIFESTACIONES CULTURALES', 'ANCHONGA, ANGARAES, HUANCAVELICA', 'ANCHONGA', 'ANGARAES', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('iglesia-de-callanmarca', 'Iglesia de Callanmarca', '', '2. MANIFESTACIONES CULTURALES', 'SECCLLA, ANGARAES, HUANCAVELICA', 'SECCLLA', 'ANGARAES', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('puente-colonial-de-callanmarca', 'Puente Colonial de Callanmarca', '', '2. MANIFESTACIONES CULTURALES', 'SECCLLA, ANGARAES, HUANCAVELICA', 'SECCLLA', 'ANGARAES', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('iglesia-de-seclla', 'Iglesia de Seclla', '', '2. MANIFESTACIONES CULTURALES', 'SECCLLA, ANGARAES, HUANCAVELICA', 'SECCLLA', 'ANGARAES', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('iglesia-matriz-de-cconccayllu', 'Iglesia Matriz de Cconccayllu', '', '2. MANIFESTACIONES CULTURALES', 'CCOCHACCASA, ANGARAES, HUANCAVELICA', 'CCOCHACCASA', 'ANGARAES', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');

INSERT INTO places (sub_place, name_place, text_place, category_place, locationName_place, district_location_place, province_location_place, region_location_place, location_place, services_place, schedule_place, price_place, access_place, recommended_time, activities_place, liked_place, created_place)
VALUES ('sitio-arqueologico-de-ccochaccasa', 'Sitio Arqueológico de Ccochaccasa', '', '2. MANIFESTACIONES CULTURALES', 'CCOCHACCASA, ANGARAES, HUANCAVELICA', 'CCOCHACCASA', 'ANGARAES', 'HUANCAVELICA', ST_GeomFromText('POINT(-75.5184 -11.9405)'), '{}', '', '', '{}', '', '{}', 0, '2025-10-30 11:40:00');